# file: roles/kafka/tasks/configure.yml

- name: Kafka | Update the kafka configuration
  template: src=usr_local_etc_kafka_config_server.properties.j2 dest=/usr/local/etc/kafka/config/server.properties owner={{ kafka_user }} group={{ kafka_group }} mode=0644
  notify:
    - restart supervisor

- name: Zookeeper | Create /var/zookeeper
  file: path=/var/zookeeper state=directory owner={{ kafka_user }} group={{ kafka_group }} mode=0755

- name: Zookeeper | Update the zookeeper configuration
  template: src=usr_local_etc_kafka_config_zookeeper.properties.j2 dest=/usr/local/etc/kafka/config/zookeeper.properties owner={{ kafka_user }} group={{ kafka_group }} mode=0644

- name: Zookeeper | Update the zookeeper id
  template: src=var_zookeeper_myid.j2 dest=/var/zookeeper/myid owner={{ kafka_user }} group={{ kafka_group }} mode=0644

  notify:
    - restart supervisor
