# file: roles/storm_common/tasks/jzmq.yml

- name: Storm | (jzmq) Download the jzmq source from the git repo
  git: repo=https://github.com/nathanmarz/jzmq.git dest=/tmp/jzmq

- name: Storm | (jzmq) Patch jzmq install for ubuntu - pt. 1
  shell: sed -i 's/classdist_noinst.stamp/classnoinst.stamp/g' src/Makefile.am chdir=/tmp/jzmq

- name: Storm | (jzmq) prepare the jzmq source
  shell: ./autogen.sh chdir=/tmp/jzmq

- name: Storm | (jzmq) configure and make the jzmq source
  shell: cd /tmp/jzmq && export JAVA_HOME=/usr/local/java/jdk && ./autogen.sh && ./configure && make -j $machine_cpu_count

- name: Storm | (jzmq) make install jzmq
  shell: cd /tmp/jzmq && sudo make install
