# file: roles/mysql/tasks/main.yml
- fail: msg="Password not set mysql_root_password"
  when: mysql_root_password is not set


- include: install.yml
- include: configure.yml
- include: secure.yml
- include: monit.yml
  when: monit_protection == true
