
- name: Storm | Install JMXtrans config
  template: src={{ item.src }} dest={{ item.dest }} owner=jmxtrans group=jmxtrans mode=0644
  with_items:
    - { src: "var_lib_jmxtrans_storm_supervisor.j2", dest: "/var/lib/jmxtrans/storm_supervisor.json" }
    - { src: "var_lib_jmxtrans_storm_worker.j2", dest: "/var/lib/jmxtrans/storm_worker.json" }
  notify:
    - restart jmxtrans
